oc_platform_home:
    path:      /
    defaults: { _controller: OCPlatformBundle:Advert:index }

oc_platform_view:
    path:      /advert/{id}
    defaults: 
      _controller: OCPlatformBundle:Advert:view
      id: 1
      
oc_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults: 
      _controller: OCPlatformBundle:Advert:viewSlug
      year: 1970
      format: html
    requirements:
      year: \d{4}
      format: html|xml

oc_platform_add:
    path:      /add
    defaults: { _controller: OCPlatformBundle:Advert:add }